# EVENT CATEGORY MAP
EVENT_CATEGORY_KAHA_GAME = T.let(:kaha_game, ::Symbol)
EVENT_CATEGORY_KAHA_DRILL = T.let(:kaha_drill, ::Symbol)
EVENT_CATEGORY_MEETUP = T.let(:meetup, ::Symbol)
EVENT_CATEGORY_REGIONAL_ADV = T.let(:regional_adventure, ::Symbol)
EVENT_CATEGORY_INTERNATIONAL_ADV = T.let(:international_adventure, ::Symbol)

EVENT_CATEGORY_KAHA_GAME_ID = T.let(0, ::Integer)
EVENT_CATEGORY_KAHA_DRILL_ID = T.let(1, ::Integer)
EVENT_CATEGORY_MEETUP_ID = T.let(2, ::Integer)
EVENT_CATEGORY_REGIONAL_ADV_ID = T.let(3, ::Integer)
EVENT_CATEGORY_INTERNATIONAL_ADV_ID = T.let(4, ::Integer)

EVENT_CATEGORYS_MAP = T.let(
  {
    EVENT_CATEGORY_KAHA_GAME => EVENT_CATEGORY_KAHA_GAME_ID,
    EVENT_CATEGORY_KAHA_DRILL => EVENT_CATEGORY_KAHA_DRILL_ID,
    EVENT_CATEGORY_MEETUP => EVENT_CATEGORY_MEETUP_ID,
    EVENT_CATEGORY_REGIONAL_ADV => EVENT_CATEGORY_REGIONAL_ADV_ID,
    EVENT_CATEGORY_INTERNATIONAL_ADV => EVENT_CATEGORY_INTERNATIONAL_ADV_ID,
  },
  T::Hash[::Symbol, ::Integer]
)
