# PARTICIPANT_STATUS MAP
PARTICIPANT_STATUS_WAITING = T.let(:waiting, ::Symbol)
PARTICIPANT_STATUS_CONFIRMED = T.let(:confirmed, ::Symbol)

PARTICIPANT_STATUS_WAITING_ID = T.let(0, ::Integer)
PARTICIPANT_STATUS_CONFIRMED_ID = T.let(1, ::Integer)

PARTICIPANT_STATUSES_MAP = T.let(
  {
    PARTICIPANT_STATUS_WAITING => PARTICIPANT_STATUS_WAITING_ID,
    PARTICIPANT_STATUS_CONFIRMED => PARTICIPANT_STATUS_CONFIRMED_ID
  },
  T::Hash[::Symbol, ::Integer]
)
